import {
  bigserial,
  boolean,
  index,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  unique,
  uuid,
} from "drizzle-orm/pg-core";

import { user } from "./auth-schema";

// Tenancy rule: every table holding business data carries business_id and
// every query is scoped by it (enforced by db/schema.test.ts). Auth tables
// live in auth-schema.ts (generated by the Better Auth CLI) and are
// instance-level infrastructure, not business data.
//
// tax_config and branding are opaque blobs here on purpose: their shape is
// owned by the billing spec (ESC-2) and the design system respectively, and
// nothing reads them yet.

export * from "./auth-schema";
export * from "./mcp-schema";

const timestamps = {
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
};

export const business = pgTable("business", {
  id: uuid("id").primaryKey().defaultRandom(),
  name: text("name").notNull(),
  // Postal address as entered, newline-separated; printed on invoices.
  address: text("address"),
  // ISO 4217 code for the business's base currency. Stored as data only -
  // all interpretation (conversion, rounding) belongs to the billing module.
  currency: text("currency").notNull(),
  // Working hours in a billing day - the divisor that turns a day rate into
  // an effective hourly rate (time is tracked in seconds, so day rates only
  // make sense relative to a day length). Business policy, read by the time
  // module at entry creation.
  hoursPerDay: integer("hours_per_day").notNull().default(8),
  taxConfig: jsonb("tax_config").notNull().default({}),
  branding: jsonb("branding").notNull().default({}),
  ...timestamps,
});

// Small teams from day one (ESC-3): users belong to one or more businesses
// through memberships, never through a column on the auth user table.
export const businessMember = pgTable(
  "business_member",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    businessId: uuid("business_id")
      .notNull()
      .references(() => business.id),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    // The role names mirror modules/authz ROLES; the column is plain text
    // (the enum is TypeScript-level only), so extending the catalog is
    // migration-free. owner carries the ownership invariants (see the team
    // service); every other role's powers come from its permission set.
    // "custom" means the member's permissions come from business_role_id (a
    // business-defined role) rather than the predefined catalog.
    role: text("role", {
      enum: [
        "owner",
        "admin",
        "manager",
        "member",
        "accountant",
        "contractor",
        "viewer",
        "custom",
      ],
    }).notNull(),
    // Set only when role is "custom": the business-defined role this member
    // holds. Null for predefined roles.
    businessRoleId: uuid("business_role_id").references(() => businessRole.id),
    ...timestamps,
  },
  (table) => [
    unique("business_member_business_user_unique").on(
      table.businessId,
      table.userId,
    ),
    index("business_member_business_id_idx").on(table.businessId),
    index("business_member_user_id_idx").on(table.userId),
  ],
);

// Custom, business-defined roles: a named bundle of permissions a business
// creates for itself beyond the predefined catalog. A member holds one via
// business_member.business_role_id (with role = "custom"). Custom roles are
// never the owner wildcard - their power is exactly their stored permission
// list, which is validated against the authz catalog at write time.
export const businessRole = pgTable(
  "business_role",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    businessId: uuid("business_id")
      .notNull()
      .references(() => business.id),
    name: text("name").notNull(),
    // authz permission strings. Unknown entries are ignored on read so a
    // retired permission can't silently grant anything.
    permissions: jsonb("permissions").notNull().default([]),
    ...timestamps,
  },
  (table) => [
    unique("business_role_business_name_unique").on(table.businessId, table.name),
    index("business_role_business_id_idx").on(table.businessId),
  ],
);

// Per-member permission overrides layered on top of the member's role: a
// `grant` adds a permission the role lacks, a `deny` removes one it has (deny
// wins). modules/authz resolves a role plus these rows into an effective
// permission set. business_id is denormalised from the member row so the
// tenancy convention stays structural (every domain table carries it).
export const businessMemberPermission = pgTable(
  "business_member_permission",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    businessId: uuid("business_id")
      .notNull()
      .references(() => business.id),
    businessMemberId: uuid("business_member_id")
      .notNull()
      .references(() => businessMember.id, { onDelete: "cascade" }),
    permission: text("permission").notNull(),
    effect: text("effect", { enum: ["grant", "deny"] }).notNull(),
    ...timestamps,
  },
  (table) => [
    unique("business_member_permission_unique").on(
      table.businessMemberId,
      table.permission,
    ),
    index("business_member_permission_member_id_idx").on(
      table.businessMemberId,
    ),
    index("business_member_permission_business_id_idx").on(table.businessId),
  ],
);

// Which business a user is currently acting in. A user can belong to several
// businesses through business_member (a clean separation of concerns - one
// account, several entities); this row records the one their requests resolve
// to until they switch. Scope is per account, not per device: switching
// carries across logins. The resolver falls back to the oldest membership when
// this is absent or stale (the pointed-at business no longer has a membership),
// so a deleted or left business can never strand the user. business_id is here
// both as the pointer and to keep the structural tenancy convention.
export const userActiveBusiness = pgTable("user_active_business", {
  userId: text("user_id")
    .primaryKey()
    .references(() => user.id, { onDelete: "cascade" }),
  businessId: uuid("business_id")
    .notNull()
    .references(() => business.id, { onDelete: "cascade" }),
  ...timestamps,
});

export const client = pgTable(
  "client",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    businessId: uuid("business_id")
      .notNull()
      .references(() => business.id),
    // The client's name - the company or organisation you invoice. Individual
    // people live in `contacts`; there is deliberately no separate company
    // field, since the name already is the company.
    name: text("name").notNull(),
    contacts: jsonb("contacts").notNull().default([]),
    notes: text("notes"),
    // Postal address as entered, newline-separated; printed on invoices in
    // the "Billed to" block. Mirrors business.address.
    address: text("address"),
    // Company / registration number (e.g. Companies House number, IČO).
    // Printed under the client on invoices when set.
    companyNumber: text("company_number"),
    // Required on reverse-charge invoices: the spec mandates both
    // parties' VAT numbers printed (Section 4).
    vatNumber: text("vat_number"),
    // Default rate in the currency's minor unit (integer, per the billing
    // spec). Stored as data; resolution happens in modules/time. The unit
    // says whether the amount is per hour or per day; a day rate is divided
    // by the business hoursPerDay into an effective hourly rate at entry
    // creation. Used when the owner works the client solo.
    defaultRateMinor: integer("default_rate_minor"),
    defaultRateCurrency: text("default_rate_currency"),
    defaultRateUnit: text("default_rate_unit", { enum: ["hour", "day"] })
      .notNull()
      .default("hour"),
    // Optional overall budget for the whole client engagement, in minor
    // units. Tracked and warned against (never enforced) by modules/reports.
    budgetMinor: integer("budget_minor"),
    budgetCurrency: text("budget_currency"),
    // Soft archive: archived clients keep their history and stay linkable
    // from old projects/invoices, they just leave the default lists.
    archivedAt: timestamp("archived_at", { withTimezone: true }),
    ...timestamps,
  },
  (table) => [index("client_business_id_idx").on(table.businessId)],
);

// Projects belong to a client of the same business; the service layer
// enforces that pairing and the integration tests prove it.
export const project = pgTable(
  "project",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    businessId: uuid("business_id")
      .notNull()
      .references(() => business.id),
    clientId: uuid("client_id")
      .notNull()
      .references(() => client.id),
    name: text("name").notNull(),
    status: text("status", {
      enum: ["active", "on_hold", "completed"],
    })
      .notNull()
      .default("active"),
    dueDate: timestamp("due_date", { withTimezone: true }),
    // Overrides the client default when set (billing spec rate precedence).
    // Unit + day-rate handling mirror the client default.
    defaultRateMinor: integer("default_rate_minor"),
    defaultRateCurrency: text("default_rate_currency"),
    defaultRateUnit: text("default_rate_unit", { enum: ["hour", "day"] })
      .notNull()
      .default("hour"),
    // Optional budget for this project, tracked like the client budget.
    budgetMinor: integer("budget_minor"),
    budgetCurrency: text("budget_currency"),
    ...timestamps,
  },
  (table) => [
    index("project_business_id_idx").on(table.businessId),
    index("project_client_id_idx").on(table.clientId),
  ],
);

// Per-client team-member pricing. A member added to a client carries the rate
// they are billed out at on that client's work (hour or day, like the client
// default), an optional internal cost (what the business actually pays them -
// margin-sensitive, exposed only with reports.viewProfit), and an optional
// per-member budget. The (client, user) pair is unique: one rate row per
// member per client. userId is the join key to time_entry.userId; the service
// validates the user is a member of the business before writing.
export const clientMemberRate = pgTable(
  "client_member_rate",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    businessId: uuid("business_id")
      .notNull()
      .references(() => business.id),
    clientId: uuid("client_id")
      .notNull()
      .references(() => client.id),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    billRateMinor: integer("bill_rate_minor").notNull(),
    billRateCurrency: text("bill_rate_currency").notNull(),
    billRateUnit: text("bill_rate_unit", { enum: ["hour", "day"] })
      .notNull()
      .default("hour"),
    // What the business pays the member (their cost), for profit tracking.
    internalCostMinor: integer("internal_cost_minor"),
    internalCostCurrency: text("internal_cost_currency"),
    internalCostUnit: text("internal_cost_unit", { enum: ["hour", "day"] })
      .notNull()
      .default("hour"),
    budgetMinor: integer("budget_minor"),
    budgetCurrency: text("budget_currency"),
    ...timestamps,
  },
  (table) => [
    unique("client_member_rate_client_user_unique").on(
      table.clientId,
      table.userId,
    ),
    index("client_member_rate_business_id_idx").on(table.businessId),
    index("client_member_rate_client_id_idx").on(table.clientId),
    index("client_member_rate_user_id_idx").on(table.userId),
  ],
);

// Time entries: a running timer is an entry with ended_at and duration
// still null. Durations are exact seconds (billing spec Section 7). The
// rate is resolved at creation (entry > project default > client default)
// and stored here with its currency so later default changes never
// reprice old work. invoice_id arrives with the billing module.
export const timeEntry = pgTable(
  "time_entry",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    businessId: uuid("business_id")
      .notNull()
      .references(() => business.id),
    taskId: uuid("task_id")
      .notNull()
      .references(() => task.id),
    userId: text("user_id")
      .notNull()
      .references(() => user.id),
    startedAt: timestamp("started_at", { withTimezone: true }).notNull(),
    endedAt: timestamp("ended_at", { withTimezone: true }),
    durationSeconds: integer("duration_seconds"),
    billable: boolean("billable").notNull().default(true),
    rateMinor: integer("rate_minor"),
    rateCurrency: text("rate_currency"),
    // The effective hourly internal cost (what the business pays the worker),
    // resolved from the client-member rate at creation and frozen here the
    // same way rateMinor is - so later rate changes never restate past profit.
    // Null when there's no internal cost (e.g. the owner working solo).
    internalCostMinor: integer("internal_cost_minor"),
    internalCostCurrency: text("internal_cost_currency"),
    note: text("note"),
    // Set when the entry is billed on an invoice line; removing that line
    // nulls it, returning the entry to the unbilled pool (spec Section 7).
    invoiceLineId: uuid("invoice_line_id").references(() => invoiceLine.id, {
      onDelete: "set null",
    }),
    ...timestamps,
  },
  (table) => [
    index("time_entry_business_id_idx").on(table.businessId),
    index("time_entry_task_id_idx").on(table.taskId),
    index("time_entry_user_id_idx").on(table.userId),
    index("time_entry_invoice_line_id_idx").on(table.invoiceLineId),
  ],
);

export const task = pgTable(
  "task",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    businessId: uuid("business_id")
      .notNull()
      .references(() => business.id),
    projectId: uuid("project_id")
      .notNull()
      .references(() => project.id),
    title: text("title").notNull(),
    status: text("status", {
      enum: ["todo", "in_progress", "in_review", "done"],
    })
      .notNull()
      .default("todo"),
    estimateMinutes: integer("estimate_minutes"),
    ...timestamps,
  },
  (table) => [
    index("task_business_id_idx").on(table.businessId),
    index("task_project_id_idx").on(table.projectId),
  ],
);

// Business expenses: a cost the business incurred, tracked as paid or
// unpaid. Amounts are integers in the currency's minor unit, consistent
// with the rest of the money model. A receipt is stored inline as a base64
// data URL (PNG/JPEG/PDF), mirroring the branding logo - no blob store to
// run when self-hosting. The data URL is deliberately excluded from list
// queries (it can be ~MBs); only the single-expense read returns it.
export const expense = pgTable(
  "expense",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    businessId: uuid("business_id")
      .notNull()
      .references(() => business.id),
    description: text("description").notNull(),
    amountMinor: integer("amount_minor").notNull(),
    currency: text("currency").notNull(),
    vendor: text("vendor"),
    category: text("category"),
    status: text("status", { enum: ["unpaid", "paid"] })
      .notNull()
      .default("unpaid"),
    // The date the cost was incurred (what the user reports on), distinct
    // from created_at (when the row was entered).
    incurredAt: timestamp("incurred_at", { withTimezone: true }).notNull(),
    // Set when marked paid, cleared when marked unpaid - the audit point.
    paidAt: timestamp("paid_at", { withTimezone: true }),
    notes: text("notes"),
    receiptDataUrl: text("receipt_data_url"),
    receiptFilename: text("receipt_filename"),
    receiptMimeType: text("receipt_mime_type"),
    ...timestamps,
  },
  (table) => [index("expense_business_id_idx").on(table.businessId)],
);

// Invitations to join a business. Membership itself lives in
// business_member; an invitation is the pending step before that row exists.
// There is no email transport when self-hosting, so an invite is a
// shareable link bearing the unguessable token - the owner sends it however
// they like, and accepting it creates the business_member row. status is the
// lifecycle (pending -> accepted | revoked); expires_at caps a stale link.
export const businessInvitation = pgTable(
  "business_invitation",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    businessId: uuid("business_id")
      .notNull()
      .references(() => business.id),
    // Lowercased invitee email - whom the invite was intended for. Shown on
    // the accept screen; not a hard auth gate (the token is the secret).
    email: text("email").notNull(),
    role: text("role", {
      enum: [
        "owner",
        "admin",
        "manager",
        "member",
        "accountant",
        "contractor",
        "viewer",
        "custom",
      ],
    })
      .notNull()
      .default("member"),
    // Set only when role is "custom": the business-defined role the invitee
    // joins as. Copied onto their membership when they accept.
    businessRoleId: uuid("business_role_id").references(() => businessRole.id),
    token: text("token").notNull().unique(),
    invitedByUserId: text("invited_by_user_id")
      .notNull()
      .references(() => user.id),
    status: text("status", { enum: ["pending", "accepted", "revoked"] })
      .notNull()
      .default("pending"),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    acceptedAt: timestamp("accepted_at", { withTimezone: true }),
    acceptedByUserId: text("accepted_by_user_id").references(() => user.id),
    ...timestamps,
  },
  (table) => [
    index("business_invitation_business_id_idx").on(table.businessId),
    index("business_invitation_token_idx").on(table.token),
  ],
);

// Invoices (billing spec Sections 4-7). Drafts carry no number; number
// and year are assigned at issue time from invoice_sequence under a row
// lock. One tax treatment per invoice; all amounts are integers in the
// invoice currency's minor unit. fx fields record a conversion applied
// to the whole invoice display only when set per line (see invoiceLine).
export const invoice = pgTable(
  "invoice",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    businessId: uuid("business_id")
      .notNull()
      .references(() => business.id),
    clientId: uuid("client_id")
      .notNull()
      .references(() => client.id),
    projectId: uuid("project_id").references(() => project.id),
    status: text("status", {
      enum: ["draft", "sent", "paid", "overdue", "void"],
    })
      .notNull()
      .default("draft"),
    // "YYYY-NNNN", unique per business; null while draft. A voided invoice
    // keeps its number - it stays a real document in the sequence (no gaps).
    number: text("number"),
    year: integer("year"),
    currency: text("currency").notNull(),
    issueDate: timestamp("issue_date", { withTimezone: true }),
    // Set when a sent/overdue invoice is voided; the optional reason is what
    // the user typed (e.g. "client address changed"), kept for the record.
    voidedAt: timestamp("voided_at", { withTimezone: true }),
    voidReason: text("void_reason"),
    dueDate: timestamp("due_date", { withTimezone: true }),
    // Optional billing period this invoice covers (e.g. a fortnight of work),
    // printed alongside the issue and due dates. Both set or both null.
    periodStart: timestamp("period_start", { withTimezone: true }),
    periodEnd: timestamp("period_end", { withTimezone: true }),
    taxTreatment: text("tax_treatment", {
      enum: ["standard", "zero_rated", "reverse_charge"],
    }).notNull(),
    taxRatePercent: text("tax_rate_percent").notNull().default("0"),
    taxNote: text("tax_note"),
    subtotalMinor: integer("subtotal_minor").notNull().default(0),
    taxMinor: integer("tax_minor").notNull().default(0),
    totalMinor: integer("total_minor").notNull().default(0),
    notes: text("notes"),
    ...timestamps,
  },
  (table) => [
    index("invoice_business_id_idx").on(table.businessId),
    index("invoice_client_id_idx").on(table.clientId),
    unique("invoice_business_number_unique").on(table.businessId, table.number),
  ],
);

export const invoiceLine = pgTable(
  "invoice_line",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    businessId: uuid("business_id")
      .notNull()
      .references(() => business.id),
    invoiceId: uuid("invoice_id")
      .notNull()
      .references(() => invoice.id, { onDelete: "cascade" }),
    position: integer("position").notNull(),
    description: text("description").notNull(),
    // Hours as an exact decimal string ("4.083333" never floats); null
    // for non-time lines (qty 1 fixed amounts).
    quantity: text("quantity"),
    unitPriceMinor: integer("unit_price_minor"),
    totalMinor: integer("total_minor").notNull(),
    // ESC-5: when the source rate currency differed, the original total
    // and the conversion applied are recorded on the line.
    sourceCurrency: text("source_currency"),
    sourceTotalMinor: integer("source_total_minor"),
    fxRate: text("fx_rate"),
    fxSource: text("fx_source", { enum: ["ecb", "manual"] }),
    ...timestamps,
  },
  (table) => [
    index("invoice_line_business_id_idx").on(table.businessId),
    index("invoice_line_invoice_id_idx").on(table.invoiceId),
  ],
);

// One row per business per year; next_number is allocated under
// SELECT ... FOR UPDATE inside the issuing transaction - no gaps, no
// duplicates, correct under concurrency (spec Section 6).
export const invoiceSequence = pgTable(
  "invoice_sequence",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    businessId: uuid("business_id")
      .notNull()
      .references(() => business.id),
    year: integer("year").notNull(),
    nextNumber: integer("next_number").notNull().default(1),
    ...timestamps,
  },
  (table) => [
    unique("invoice_sequence_business_year_unique").on(
      table.businessId,
      table.year,
    ),
  ],
);

// The client activity thread: notes written by users plus automatic
// lifecycle events. payload shape depends on type and is owned by
// modules/clients. The enum is TypeScript-level only (the column is
// plain text), so extending it is migration-free.
export const activity = pgTable(
  "activity",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    // Monotonic insertion order: `at` timestamps can collide within a
    // microsecond, and the thread must render in a stable order.
    seq: bigserial("seq", { mode: "number" }).notNull(),
    businessId: uuid("business_id")
      .notNull()
      .references(() => business.id),
    clientId: uuid("client_id")
      .notNull()
      .references(() => client.id),
    userId: text("user_id").references(() => user.id),
    type: text("type", {
      enum: [
        "note",
        "client_created",
        "client_updated",
        "client_archived",
        "client_unarchived",
        "project_created",
        "invoice_voided",
      ],
    }).notNull(),
    payload: jsonb("payload").notNull().default({}),
    at: timestamp("at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    index("activity_business_id_idx").on(table.businessId),
    index("activity_client_id_idx").on(table.clientId),
  ],
);
