import {
  bigserial,
  index,
  jsonb,
  pgTable,
  text,
  timestamp,
  unique,
  uuid,
} from "drizzle-orm/pg-core";

import { user } from "./auth-schema";

// Tenancy rule: every table holding business data carries business_id and
// every query is scoped by it (enforced by db/schema.test.ts). Auth tables
// live in auth-schema.ts (generated by the Better Auth CLI) and are
// instance-level infrastructure, not business data.
//
// tax_config and branding are opaque blobs here on purpose: their shape is
// owned by the billing spec (ESC-2) and the design system respectively, and
// nothing reads them yet.

export * from "./auth-schema";

const timestamps = {
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
};

export const business = pgTable("business", {
  id: uuid("id").primaryKey().defaultRandom(),
  name: text("name").notNull(),
  // ISO 4217 code for the business's base currency. Stored as data only -
  // all interpretation (conversion, rounding) belongs to the billing module.
  currency: text("currency").notNull(),
  taxConfig: jsonb("tax_config").notNull().default({}),
  branding: jsonb("branding").notNull().default({}),
  ...timestamps,
});

// Small teams from day one (ESC-3): users belong to one or more businesses
// through memberships, never through a column on the auth user table.
export const businessMember = pgTable(
  "business_member",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    businessId: uuid("business_id")
      .notNull()
      .references(() => business.id),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    role: text("role", { enum: ["owner", "member"] }).notNull(),
    ...timestamps,
  },
  (table) => [
    unique("business_member_business_user_unique").on(
      table.businessId,
      table.userId,
    ),
    index("business_member_business_id_idx").on(table.businessId),
    index("business_member_user_id_idx").on(table.userId),
  ],
);

export const client = pgTable(
  "client",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    businessId: uuid("business_id")
      .notNull()
      .references(() => business.id),
    name: text("name").notNull(),
    company: text("company"),
    contacts: jsonb("contacts").notNull().default([]),
    notes: text("notes"),
    // Soft archive: archived clients keep their history and stay linkable
    // from old projects/invoices, they just leave the default lists.
    archivedAt: timestamp("archived_at", { withTimezone: true }),
    ...timestamps,
  },
  (table) => [index("client_business_id_idx").on(table.businessId)],
);

// Projects belong to a client of the same business; the service layer
// enforces that pairing and the integration tests prove it.
export const project = pgTable(
  "project",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    businessId: uuid("business_id")
      .notNull()
      .references(() => business.id),
    clientId: uuid("client_id")
      .notNull()
      .references(() => client.id),
    name: text("name").notNull(),
    status: text("status", {
      enum: ["active", "on_hold", "completed"],
    })
      .notNull()
      .default("active"),
    dueDate: timestamp("due_date", { withTimezone: true }),
    ...timestamps,
  },
  (table) => [
    index("project_business_id_idx").on(table.businessId),
    index("project_client_id_idx").on(table.clientId),
  ],
);

// The client activity thread: notes written by users plus automatic
// lifecycle events. payload shape depends on type and is owned by
// modules/clients. The enum is TypeScript-level only (the column is
// plain text), so extending it is migration-free.
export const activity = pgTable(
  "activity",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    // Monotonic insertion order: `at` timestamps can collide within a
    // microsecond, and the thread must render in a stable order.
    seq: bigserial("seq", { mode: "number" }).notNull(),
    businessId: uuid("business_id")
      .notNull()
      .references(() => business.id),
    clientId: uuid("client_id")
      .notNull()
      .references(() => client.id),
    userId: text("user_id").references(() => user.id),
    type: text("type", {
      enum: [
        "note",
        "client_created",
        "client_updated",
        "client_archived",
        "client_unarchived",
        "project_created",
      ],
    }).notNull(),
    payload: jsonb("payload").notNull().default({}),
    at: timestamp("at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    index("activity_business_id_idx").on(table.businessId),
    index("activity_client_id_idx").on(table.clientId),
  ],
);
