import {
  bigserial,
  boolean,
  index,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  unique,
  uuid,
} from "drizzle-orm/pg-core";

import { user } from "./auth-schema";

// Tenancy rule: every table holding business data carries business_id and
// every query is scoped by it (enforced by db/schema.test.ts). Auth tables
// live in auth-schema.ts (generated by the Better Auth CLI) and are
// instance-level infrastructure, not business data.
//
// tax_config and branding are opaque blobs here on purpose: their shape is
// owned by the billing spec (ESC-2) and the design system respectively, and
// nothing reads them yet.

export * from "./auth-schema";

const timestamps = {
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
};

export const business = pgTable("business", {
  id: uuid("id").primaryKey().defaultRandom(),
  name: text("name").notNull(),
  // ISO 4217 code for the business's base currency. Stored as data only -
  // all interpretation (conversion, rounding) belongs to the billing module.
  currency: text("currency").notNull(),
  taxConfig: jsonb("tax_config").notNull().default({}),
  branding: jsonb("branding").notNull().default({}),
  ...timestamps,
});

// Small teams from day one (ESC-3): users belong to one or more businesses
// through memberships, never through a column on the auth user table.
export const businessMember = pgTable(
  "business_member",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    businessId: uuid("business_id")
      .notNull()
      .references(() => business.id),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    role: text("role", { enum: ["owner", "member"] }).notNull(),
    ...timestamps,
  },
  (table) => [
    unique("business_member_business_user_unique").on(
      table.businessId,
      table.userId,
    ),
    index("business_member_business_id_idx").on(table.businessId),
    index("business_member_user_id_idx").on(table.userId),
  ],
);

export const client = pgTable(
  "client",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    businessId: uuid("business_id")
      .notNull()
      .references(() => business.id),
    name: text("name").notNull(),
    company: text("company"),
    contacts: jsonb("contacts").notNull().default([]),
    notes: text("notes"),
    // Default hourly rate in the currency's minor unit (integer, per the
    // billing spec). Stored as data; resolution happens in modules/time.
    defaultRateMinor: integer("default_rate_minor"),
    defaultRateCurrency: text("default_rate_currency"),
    // Soft archive: archived clients keep their history and stay linkable
    // from old projects/invoices, they just leave the default lists.
    archivedAt: timestamp("archived_at", { withTimezone: true }),
    ...timestamps,
  },
  (table) => [index("client_business_id_idx").on(table.businessId)],
);

// Projects belong to a client of the same business; the service layer
// enforces that pairing and the integration tests prove it.
export const project = pgTable(
  "project",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    businessId: uuid("business_id")
      .notNull()
      .references(() => business.id),
    clientId: uuid("client_id")
      .notNull()
      .references(() => client.id),
    name: text("name").notNull(),
    status: text("status", {
      enum: ["active", "on_hold", "completed"],
    })
      .notNull()
      .default("active"),
    dueDate: timestamp("due_date", { withTimezone: true }),
    // Overrides the client default when set (billing spec rate precedence).
    defaultRateMinor: integer("default_rate_minor"),
    defaultRateCurrency: text("default_rate_currency"),
    ...timestamps,
  },
  (table) => [
    index("project_business_id_idx").on(table.businessId),
    index("project_client_id_idx").on(table.clientId),
  ],
);

// Time entries: a running timer is an entry with ended_at and duration
// still null. Durations are exact seconds (billing spec Section 7). The
// rate is resolved at creation (entry > project default > client default)
// and stored here with its currency so later default changes never
// reprice old work. invoice_id arrives with the billing module.
export const timeEntry = pgTable(
  "time_entry",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    businessId: uuid("business_id")
      .notNull()
      .references(() => business.id),
    taskId: uuid("task_id")
      .notNull()
      .references(() => task.id),
    userId: text("user_id")
      .notNull()
      .references(() => user.id),
    startedAt: timestamp("started_at", { withTimezone: true }).notNull(),
    endedAt: timestamp("ended_at", { withTimezone: true }),
    durationSeconds: integer("duration_seconds"),
    billable: boolean("billable").notNull().default(true),
    rateMinor: integer("rate_minor"),
    rateCurrency: text("rate_currency"),
    note: text("note"),
    // Set when the entry is billed on an invoice line; removing that line
    // nulls it, returning the entry to the unbilled pool (spec Section 7).
    invoiceLineId: uuid("invoice_line_id").references(() => invoiceLine.id, {
      onDelete: "set null",
    }),
    ...timestamps,
  },
  (table) => [
    index("time_entry_business_id_idx").on(table.businessId),
    index("time_entry_task_id_idx").on(table.taskId),
    index("time_entry_user_id_idx").on(table.userId),
    index("time_entry_invoice_line_id_idx").on(table.invoiceLineId),
  ],
);

export const task = pgTable(
  "task",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    businessId: uuid("business_id")
      .notNull()
      .references(() => business.id),
    projectId: uuid("project_id")
      .notNull()
      .references(() => project.id),
    title: text("title").notNull(),
    status: text("status", {
      enum: ["todo", "in_progress", "in_review", "done"],
    })
      .notNull()
      .default("todo"),
    estimateMinutes: integer("estimate_minutes"),
    ...timestamps,
  },
  (table) => [
    index("task_business_id_idx").on(table.businessId),
    index("task_project_id_idx").on(table.projectId),
  ],
);

// Invoices (billing spec Sections 4-7). Drafts carry no number; number
// and year are assigned at issue time from invoice_sequence under a row
// lock. One tax treatment per invoice; all amounts are integers in the
// invoice currency's minor unit. fx fields record a conversion applied
// to the whole invoice display only when set per line (see invoiceLine).
export const invoice = pgTable(
  "invoice",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    businessId: uuid("business_id")
      .notNull()
      .references(() => business.id),
    clientId: uuid("client_id")
      .notNull()
      .references(() => client.id),
    projectId: uuid("project_id").references(() => project.id),
    status: text("status", {
      enum: ["draft", "sent", "paid", "overdue"],
    })
      .notNull()
      .default("draft"),
    // "YYYY-NNNN", unique per business; null while draft.
    number: text("number"),
    year: integer("year"),
    currency: text("currency").notNull(),
    issueDate: timestamp("issue_date", { withTimezone: true }),
    dueDate: timestamp("due_date", { withTimezone: true }),
    taxTreatment: text("tax_treatment", {
      enum: ["standard", "zero_rated", "reverse_charge"],
    }).notNull(),
    taxRatePercent: text("tax_rate_percent").notNull().default("0"),
    taxNote: text("tax_note"),
    subtotalMinor: integer("subtotal_minor").notNull().default(0),
    taxMinor: integer("tax_minor").notNull().default(0),
    totalMinor: integer("total_minor").notNull().default(0),
    notes: text("notes"),
    ...timestamps,
  },
  (table) => [
    index("invoice_business_id_idx").on(table.businessId),
    index("invoice_client_id_idx").on(table.clientId),
    unique("invoice_business_number_unique").on(table.businessId, table.number),
  ],
);

export const invoiceLine = pgTable(
  "invoice_line",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    businessId: uuid("business_id")
      .notNull()
      .references(() => business.id),
    invoiceId: uuid("invoice_id")
      .notNull()
      .references(() => invoice.id, { onDelete: "cascade" }),
    position: integer("position").notNull(),
    description: text("description").notNull(),
    // Hours as an exact decimal string ("4.083333" never floats); null
    // for non-time lines (qty 1 fixed amounts).
    quantity: text("quantity"),
    unitPriceMinor: integer("unit_price_minor"),
    totalMinor: integer("total_minor").notNull(),
    // ESC-5: when the source rate currency differed, the original total
    // and the conversion applied are recorded on the line.
    sourceCurrency: text("source_currency"),
    sourceTotalMinor: integer("source_total_minor"),
    fxRate: text("fx_rate"),
    fxSource: text("fx_source", { enum: ["ecb", "manual"] }),
    ...timestamps,
  },
  (table) => [
    index("invoice_line_business_id_idx").on(table.businessId),
    index("invoice_line_invoice_id_idx").on(table.invoiceId),
  ],
);

// One row per business per year; next_number is allocated under
// SELECT ... FOR UPDATE inside the issuing transaction - no gaps, no
// duplicates, correct under concurrency (spec Section 6).
export const invoiceSequence = pgTable(
  "invoice_sequence",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    businessId: uuid("business_id")
      .notNull()
      .references(() => business.id),
    year: integer("year").notNull(),
    nextNumber: integer("next_number").notNull().default(1),
    ...timestamps,
  },
  (table) => [
    unique("invoice_sequence_business_year_unique").on(
      table.businessId,
      table.year,
    ),
  ],
);

// The client activity thread: notes written by users plus automatic
// lifecycle events. payload shape depends on type and is owned by
// modules/clients. The enum is TypeScript-level only (the column is
// plain text), so extending it is migration-free.
export const activity = pgTable(
  "activity",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    // Monotonic insertion order: `at` timestamps can collide within a
    // microsecond, and the thread must render in a stable order.
    seq: bigserial("seq", { mode: "number" }).notNull(),
    businessId: uuid("business_id")
      .notNull()
      .references(() => business.id),
    clientId: uuid("client_id")
      .notNull()
      .references(() => client.id),
    userId: text("user_id").references(() => user.id),
    type: text("type", {
      enum: [
        "note",
        "client_created",
        "client_updated",
        "client_archived",
        "client_unarchived",
        "project_created",
      ],
    }).notNull(),
    payload: jsonb("payload").notNull().default({}),
    at: timestamp("at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    index("activity_business_id_idx").on(table.businessId),
    index("activity_client_id_idx").on(table.clientId),
  ],
);
